
# NB! If you want use shared composer volume:
# 1. Create composer container: docker create -v $HOME/.composer:/.composer --name composer busybox:1.25 /bin/true
# 2. Uncomment "volumes_from" part from "php" servece

services:
    mysql:
        image: mysql:5
        env:
            MYSQL_ROOT_PASSWORD: '123123'
        volumes:
            .whaler/mysql/my.cnf: /etc/my.cnf

    postfix:
        image: previousnext/postfix

    php:
        wait: 30m
        image: modera/php:5
        env:
            SYMFONY__db_host: mysql
            SYMFONY__db_port: 3306
            SYMFONY__db_user: root
            SYMFONY__db_password: 123123
#        volumes_from:
#            - container:composer
        volumes:
            .: /var/www
        cmd: .whaler/php/run.sh

    nginx:
        web: 80
#        ssl: 8443 send-proxy
        image: nginx:1.7.7
        volumes:
            .: /var/www
            .whaler/nginx/nginx.conf: /etc/nginx/nginx.conf
        cmd: nginx
