
# NB! If you want use shared composer volume:
# 1. Create volume: docker volume create composer
# 2. Uncomment "composer" parts

services:
    mysql:
        image: mysql:5
        env:
            MYSQL_ROOT_PASSWORD: '123123'
        volumes:
            .whaler/mysql/my.cnf: /etc/my.cnf

    postfix:
        image: previousnext/postfix

    php:
        wait: 30m
        image: modera/php:7.2
        env:
            SYMFONY__db_host: mysql
            SYMFONY__db_port: 3306
            SYMFONY__db_user: root
            SYMFONY__db_password: 123123
        volumes:
            .: /var/www
#            composer: /.composer
        cmd: .whaler/php/run.sh

    nginx:
        web: 80
#        ssl: 8443 send-proxy
        image: nginx:1.15
        volumes:
            .: /var/www
            .whaler/nginx/nginx.conf: /etc/nginx/nginx.conf
        cmd: nginx

volumes:
#    composer:
#        external: true
